# Generated by Django 5.0.4 on 2024-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=15)),
                ('uname', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=10)),
                ('cpassw', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
